export default {
  FETCHING_ASSIGNMENTS_DETAILS: 'FETCHING_ASSIGNMENTS_DETAILS',
  FETCHING_ASSIGNMENTS_DETAILS_SUCCESS: 'FETCHING_ASSIGNMENTS_DETAILS_SUCCESS',
  FETCHING_ASSIGNMENTS_DETAILS_FAILURE: 'FETCHING_ASSIGNMENTS_DETAILS_FAILURE'
};
