export default {
  CREATE_ASSIGNMENT_WITH_GRADES: 'CREATE_ASSIGNMENT_WITH_GRADES',
  CREATE_ASSIGNMENT_WITH_GRADES_SUCCESS: 'CREATE_ASSIGNMENT_WITH_GRADES_SUCCESS',
  CREATE_ASSIGNMENT_WITH_GRADES_FAILURE: 'CREATE_ASSIGNMENT_WITH_GRADES_FAILURE'
};
