export default {
  CREATE_ASSIGNMENT_WITH_GRADES: 'CREATE_ASSIGNMENT_WITH_GRADES',
  CREATE_ASSIGNMENT_WITH_GRADES_SUCCESS: 'CREATE_ASSIGNMENT_WITH_GRADES_SUCCESS',
  CREATE_ASSIGNMENT_WITH_GRADES_FAILURE: 'CREATE_ASSIGNMENT_WITH_GRADES_FAILURE',

  EDIT_ASSIGNMENT_WITH_GRADES: 'EDIT_ASSIGNMENT_WITH_GRADES',
  EDIT_ASSIGNMENT_WITH_GRADES_SUCCESS: 'EDIT_ASSIGNMENT_WITH_GRADES_SUCCESS',
  EDIT_ASSIGNMENT_WITH_GRADES_FAILURE: 'EDIT_ASSIGNMENT_WITH_GRADES_FAILURE'
};
