export default {
  FETCHING_ASSIGNMENTS_LIST: 'FETCHING_ASSIGNMENTS_LIST',
  FETCHING_ASSIGNMENTS_LIST_SUCCESS: 'FETCHING_ASSIGNMENTS_LIST_SUCCESS',
  FETCHING_ASSIGNMENTS_LIST_FAILURE: 'FETCHING_ASSIGNMENTS_LIST_FAILURE'
};
