export default {
  CREATE_ABSENCE: 'CREATE_ABSENCE',
  CREATE_ABSENCE_SUCCESS: 'CREATE_ABSENCE_SUCCESS',
  CREATE_ABSENCE_FAILURE: 'CREATE_ABSENCE_FAILUREE',
  EDIT_ABSENCE: 'EDIT_ABSENCE',
  EDIT_ABSENCE_SUCCESS: 'EDIT_ABSENCE_SUCCESS',
  EDIT_ABSENCE_FAILURE: 'EDIT_ABSENCE_FAILURE'
};
