export default {
  FETCHING_ABSENCES_LIST: 'FETCHING_ABSENCES_LIST',
  FETCHING_ABSENCES_LIST_SUCCESS: 'FETCHING_ABSENCES_LIST_SUCCESS',
  FETCHING_ABSENCES_LIST_FAILURE: 'FETCHING_ABSENCES_LIST_FAILURE'
};
