export default {
  FETCHING_PROMO_ABSENCE_PODIUM: 'FETCHING_PROMO_ABSENCE_PODIUM',
  FETCHING_PROMO_ABSENCE_PODIUM_SUCCESS: 'FETCHING_PROMO_ABSENCE_PODIUM_SUCCESS',
  FETCHING_PROMO_ABSENCE_PODIUM_FAILURE: 'FETCHING_PROMO_ABSENCE_PODIUM_FAILURE'
};
