export default {
  FETCHING_ABSENCES_WEEK_GRAPH_LIST: 'FETCHING_ABSENCES_WEEK_GRAPH_LIST',
  FETCHING_ABSENCES_WEEK_GRAPH_LIST_SUCCESS: 'FETCHING_ABSENCES_WEEK_GRAPH_LIST_SUCCESS',
  FETCHING_ABSENCES_WEEK_GRAPH_LIST_FAILURE: 'FETCHING_ABSENCES_WEEK_GRAPH_LIST_FAILURE'
};
