export default {
  CREATE_SUBJECT_WITH_GRADES: 'CREATE_SUBJECT_WITH_GRADES',
  CREATE_SUBJECT_WITH_GRADES_SUCCESS: 'CREATE_SUBJECT_WITH_GRADES_SUCCESS',
  CREATE_SUBJECT_WITH_GRADES_FAILURE: 'CREATE_SUBJECT_WITH_GRADES_FAILURE'
};
