export default {
  FETCHING_SEMESTERS_LIST: 'FETCHING_SEMESTERS_LIST',
  FETCHING_SEMESTERS_LIST_SUCCESS: 'FETCHING_SEMESTERS_LIST_SUCCESS',
  FETCHING_SEMESTERS_LIST_FAILURE: 'FETCHING_SEMESTERS_LIST_FAILURE'
};
