export default {
  FETCHING_COURSES_LIST: 'FETCHING_COURSES_LIST',
  FETCHING_COURSES_LIST_SUCCESS: 'FETCHING_COURSES_DETAILS_SUCCESS',
  FETCHING_COURSES_LIST_FAILURE: 'FETCHING_COURSES_DETAILS_FAILURE'
};
