export default {
  FILTERING: 'FILTERING',
  RESET_FILTER: 'RESET_FILTER',
  SET_VISIBILITY_FILTER: 'SET_VISIBILITY_FILTER',

  SHOW_ALL: 'SHOW_ALL',
  SHOW_TD_1: 'SHOW_TD_1',
  SHOW_TD_2: 'SHOW_TD_2',

  FILTER_GRADES: 'FILTER_GRADES'
};
