export default {
  FETCHING_PROMOTIONS_DETAILS: 'FETCHING_PROMOTIONS_DETAILS',
  FETCHING_PROMOTIONS_DETAILS_SUCCESS: 'FETCHING_PROMOTIONS_DETAILS_SUCCESS',
  FETCHING_PROMOTIONS_DETAILS_FAILURE: 'FETCHING_PROMOTIONS_DETAILS_FAILURE'
};
