export default {
  FETCHING_PROMOTIONS_LIST: 'FETCHING_PROMOTIONS_LIST',
  FETCHING_PROMOTIONS_LIST_SUCCESS: 'FETCHING_PROMOTIONS_LIST_SUCCESS',
  FETCHING_PROMOTIONS_LIST_FAILURE: 'FETCHING_PROMOTIONS_LIST_FAILURE'
};
