export default {
  FETCHING_STUDENT_DETAILS: 'FETCHING_STUDENT_DETAILS',
  FETCHING_STUDENT_DETAILS_SUCCESS: 'FETCHING_STUDENT_DETAILS_SUCCESS',
  FETCHING_STUDENT_DETAILS_FAILURE: 'FETCHING_STUDENT_DETAILS_FAILURE'
};
