export default {
  FETCHING_SUBJECTS_LIST: 'FETCHING_SUBJECTS_LIST',
  FETCHING_SUBJECTS_LIST_SUCCESS: 'FETCHING_SUBJECTS_DETAILS_SUCCESS',
  FETCHING_SUBJECTS_LIST_FAILURE: 'FETCHING_SUBJECTS_DETAILS_FAILURE'
};
